### ISSUE TITLE
Tracing info is not being generated with deployment target set to "Architect (AWS Lambda)"

### ISSUE THREAD

**Issue by lpsinger** [justindsmith/opentelemetry-instrumentations-js#33]
I am using opentelemetry-instrumentation-remix with an application that uses Remix's "Architect (AWS Lambda)" deployment target. When I deploy to AWS, I do get tracing info for AWS SDK calls etc. but I do not get any of the spans from opentelemetry-instrumentation-remix.

I made a simple reproducer, https://github.com/lpsinger/remix-architect-instrumentation, and I get no tracing info at all when I run it in "sandbox" mode via `npm run dev`.

**Comment by justindsmith** [comment]
I suspect this is something to do with Architect / lambda instrumentation and not the remix instrumentation. I setup your reproducer (thanks!) and added some comments to the instrumentation logic and it _was_ getting patched and was at least starting and ending the associated span.

<img width="608" alt="image" src="https://user-images.githubusercontent.com/157923/213938433-d6058352-cf68-44f4-b6eb-62f3d358bda9.png">

I looked for instrumentation details for lambda and found this blog post: https://www.aspecto.io/blog/how-to-use-opentelemetry-with-aws-lambda/

Following those instructions I updated your `tracing.js` with the following and I _did_ see spans getting emitted on the console. So I assume it's something to do with the NodeSDK in lambda functions not working as expected.

Hopefully this helps!

`tracing.js`
```javascript
const { SimpleSpanProcessor, ConsoleSpanExporter } = require("@opentelemetry/sdk-trace-base");
const { NodeTracerProvider } = require('@opentelemetry/sdk-trace-node');
const { AwsLambdaInstrumentation } = require('@opentelemetry/instrumentation-aws-lambda');
const { registerInstrumentations } = require('@opentelemetry/instrumentation');
const { getNodeAutoInstrumentations } = require("@opentelemetry/auto-instrumentations-node");
const { RemixInstrumentation } = require("opentelemetry-instrumentation-remix");

const provider = new NodeTracerProvider();
provider.addSpanProcessor(new SimpleSpanProcessor(new ConsoleSpanExporter()))
provider.register();
registerInstrumentations({
 instrumentations: [
   getNodeAutoInstrumentations(),
   new AwsLambdaInstrumentation({
     disableAwsContextPropagation: true
   })
   , new RemixInstrumentation()
 ],
});```

**Comment by lpsinger** [comment]
The problem on AWS Lambda turned out to be that I had to pass both the RemixInstrumentation object _and_ the tracer to `registerInstrumentations`. This was a bit tricky to do since I was using AWS Distro for OpenTelemetry (https://aws-otel.github.io/docs/getting-started/lambda/lambda-js) and their wrapper script (https://github.com/open-telemetry/opentelemetry-lambda/blob/main/nodejs/packages/layer/src/wrapper.ts) doesn't provide an easy way to inject your own instrumentations.

I opened a PR to make it a bit easier to add custom instrumentations: https://github.com/open-telemetry/opentelemetry-lambda/pull/435
